name: 🔧 Claude 수정 작업
description: Claude Code에게 문제 해결이나 수정 작업을 지시하기 위한 템플릿입니다.
title: "[FIX] "
labels: ["fix", "claude"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🔧 Claude Code 수정 작업 지시서
        
        Claude Code에게 문제 해결이나 기존 코드 수정 작업을 지시하기 위한 템플릿입니다.
        구체적인 문제 상황과 해결 방향을 제시해주세요.

  - type: textarea
    id: problem_description
    attributes:
      label: 🐛 문제 상황
      description: 현재 발생하고 있는 문제나 수정이 필요한 부분을 상세히 설명해주세요.
      placeholder: |
        예시:
        - 모바일에서 네비게이션 메뉴가 제대로 표시되지 않음
        - 다크모드에서 텍스트 색상이 보이지 않음
        - 블로그 포스트 로딩 속도가 너무 느림
        - 검색 결과가 정확하지 않음
        - 특정 브라우저에서 레이아웃이 깨짐
    validations:
      required: true

  - type: textarea
    id: current_behavior
    attributes:
      label: ❌ 현재 동작
      description: 현재 어떻게 동작하고 있는지 구체적으로 설명해주세요.
      placeholder: |
        예시:
        - 모바일에서 햄버거 메뉴를 클릭해도 아무 반응이 없음
        - 다크모드에서 제목 텍스트가 검은색으로 표시되어 보이지 않음
        - 페이지 로드 시간이 5초 이상 소요됨
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: ✅ 원하는 동작
      description: 어떻게 수정되어야 하는지 명확하게 설명해주세요.
      placeholder: |
        예시:
        - 모바일에서 햄버거 메뉴 클릭 시 네비게이션 메뉴가 펼쳐져야 함
        - 다크모드에서 제목 텍스트가 흰색으로 표시되어야 함
        - 페이지 로드 시간이 2초 이내로 단축되어야 함
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: 🔄 재현 방법
      description: 문제를 재현할 수 있는 단계를 상세히 설명해주세요.
      placeholder: |
        1. 사이트 접속
        2. 모바일 화면 크기로 변경
        3. 햄버거 메뉴 클릭
        4. 문제 확인
    validations:
      required: true

  - type: dropdown
    id: fix_type
    attributes:
      label: 🏷️ 수정 유형
      description: 어떤 종류의 수정 작업인가요?
      options:
        - 버그 수정
        - 스타일/레이아웃 수정
        - 성능 최적화
        - 기능 개선
        - 호환성 문제 해결
        - 보안 취약점 수정
        - 코드 리팩토링
        - 기타
      default: 0
    validations:
      required: true

  - type: dropdown
    id: urgency
    attributes:
      label: 🚨 긴급도
      description: 수정 작업의 긴급도를 선택해주세요.
      options:
        - 🔴 긴급 (즉시 수정 필요)
        - 🟡 보통 (일반적인 수정)
        - 🟢 낮음 (시간 여유 있음)
      default: 1
    validations:
      required: true

  - type: textarea
    id: affected_files
    attributes:
      label: 📁 관련 파일
      description: 문제가 발생한 파일이나 수정이 필요한 파일 경로를 알고 있다면 명시해주세요.
      placeholder: |
        예시:
        - src/app/_components/Navigation.tsx
        - src/app/globals.css
        - src/app/layout.tsx

  - type: textarea
    id: error_logs
    attributes:
      label: 📋 에러 로그
      description: 콘솔 에러나 로그가 있다면 붙여넣어 주세요.
      placeholder: |
        콘솔 에러, 빌드 에러, 또는 기타 관련 로그를 여기에 붙여넣어 주세요.

  - type: textarea
    id: environment_info
    attributes:
      label: 🌐 환경 정보
      description: 문제가 발생하는 환경 정보를 제공해주세요.
      placeholder: |
        예시:
        - 브라우저: Chrome 120.0.0.0
        - 운영체제: macOS 14.0
        - 디바이스: iPhone 15 Pro
        - 화면 크기: 375x812

  - type: textarea
    id: additional_context
    attributes:
      label: 📝 추가 정보
      description: 문제 해결에 도움이 될 추가적인 정보가 있나요?
      placeholder: |
        - 최근 변경사항
        - 관련 이슈나 PR
        - 참고할 만한 자료
        - 기타 컨텍스트 정보