name: 🤖 Claude 작업 지시
description: Claude Code에게 작업을 지시하기 위한 템플릿입니다.
title: "[TASK] "
labels: ["task", "claude"]
body:
  - type: markdown
    attributes:
      value: |
        ## 💡 Claude Code 작업 지시서
        
        Claude Code에게 개발 작업을 지시하기 위한 템플릿입니다.
        구체적이고 명확한 지시를 통해 효과적인 작업을 진행해보세요.

  - type: textarea
    id: task_description
    attributes:
      label: 📋 작업 내용
      description: Claude에게 수행시키고 싶은 작업을 구체적으로 설명해주세요.
      placeholder: |
        예시:
        - 블로그에 검색 기능 추가해줘
        - 다크모드 토글 버튼 구현
        - 반응형 네비게이션 메뉴 만들기
        - 포스트 페이지네이션 기능 추가
        - 코드 블록 복사 버튼 추가
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: 📌 요구사항
      description: 작업 시 고려해야 할 조건이나 제약사항이 있나요?
      placeholder: |
        예시:
        - TypeScript 사용해서 작성
        - 모바일 환경에서도 잘 작동해야 함
        - 기존 UI/UX와 일관성 유지
        - 성능 최적화 고려
        - 접근성 고려사항

  - type: dropdown
    id: task_type
    attributes:
      label: 🏷️ 작업 유형
      description: 어떤 종류의 작업인가요?
      options:
        - 새로운 기능 구현
        - 기존 기능 개선
        - 버그 수정
        - 리팩토링
        - UI/UX 개선
        - 성능 최적화
        - 테스트 코드 작성
        - 문서 작성
        - 기타
      default: 0
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 🔥 우선순위
      description: 작업의 우선순위를 선택해주세요.
      options:
        - 🔴 높음 (즉시 처리 필요)
        - 🟡 보통 (일반적인 작업)
        - 🟢 낮음 (시간 여유 있음)
      default: 1
    validations:
      required: true

  - type: textarea
    id: technical_details
    attributes:
      label: 🔧 기술적 세부사항
      description: 구현에 필요한 기술적 정보나 참고사항이 있나요?
      placeholder: |
        예시:
        - 특정 라이브러리나 패키지 사용
        - API 엔드포인트 정보
        - 데이터 구조나 스키마
        - 관련 파일 경로
        - 참고할 기존 코드

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: ✅ 완료 조건
      description: 작업이 완료되었다고 판단할 수 있는 조건들을 명시해주세요.
      placeholder: |
        예시:
        - [ ] 검색창에서 키워드 입력 시 관련 포스트 표시
        - [ ] 모바일에서도 정상 작동 확인
        - [ ] 빌드 및 테스트 통과
        - [ ] 코드 품질 검사 통과
        - [ ] 브라우저 호환성 확인

  - type: textarea
    id: references
    attributes:
      label: 📚 참고 자료
      description: 작업에 도움이 될 참고 자료나 링크가 있나요?
      placeholder: |
        예시:
        - 관련 문서나 가이드 링크
        - 참고할 사이트나 예시
        - 관련 GitHub 이슈나 PR
        - 디자인 시안이나 목업