name: 🧪 Claude 테스트 작성
description: Claude Code에게 테스트 코드 작성을 지시하기 위한 템플릿입니다.
title: "[TEST] "
labels: ["test", "claude"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🧪 Claude Code 테스트 작성 지시서
        
        Claude Code에게 테스트 코드 작성이나 테스트 개선 작업을 지시하기 위한 템플릿입니다.
        테스트할 대상과 범위를 명확히 제시해주세요.

  - type: textarea
    id: test_target
    attributes:
      label: 🎯 테스트 대상
      description: 테스트를 작성할 대상 코드를 구체적으로 설명해주세요.
      placeholder: |
        예시:
        - src/app/_components/Navigation.tsx의 메뉴 토글 기능
        - src/api/posts.ts의 블로그 포스트 데이터 fetching 함수
        - src/app/_lib/utils.ts의 유틸리티 함수들
        - src/app/blog/[slug]/page.tsx의 동적 라우팅 페이지
        - 전체 블로그 포스트 렌더링 플로우
    validations:
      required: true

  - type: dropdown
    id: test_type
    attributes:
      label: 🏷️ 테스트 유형
      description: 어떤 종류의 테스트를 작성하고 싶나요?
      options:
        - 단위 테스트 (Unit Test)
        - 통합 테스트 (Integration Test)
        - 컴포넌트 테스트 (Component Test)
        - E2E 테스트 (End-to-End Test)
        - 스냅샷 테스트 (Snapshot Test)
        - 성능 테스트 (Performance Test)
        - 접근성 테스트 (Accessibility Test)
        - 기타
      default: 0
    validations:
      required: true

  - type: textarea
    id: test_scenarios
    attributes:
      label: 📝 테스트 시나리오
      description: 테스트해야 할 구체적인 시나리오들을 나열해주세요.
      placeholder: |
        예시:
        - 사용자가 햄버거 메뉴를 클릭했을 때 네비게이션이 열리는지 확인
        - 잘못된 slug로 접근했을 때 404 페이지가 표시되는지 확인
        - 블로그 포스트 데이터가 올바르게 파싱되는지 확인
        - 다크모드 토글이 정상적으로 작동하는지 확인
        - 모바일 환경에서 레이아웃이 올바르게 표시되는지 확인
    validations:
      required: true

  - type: textarea
    id: test_cases
    attributes:
      label: ✅ 테스트 케이스
      description: 검증해야 할 구체적인 테스트 케이스들을 명시해주세요.
      placeholder: |
        예시:
        - [ ] 정상적인 입력값에 대한 올바른 결과 반환
        - [ ] 빈 값이나 null 입력에 대한 적절한 처리
        - [ ] 잘못된 형식의 입력에 대한 에러 처리
        - [ ] 경계값 테스트 (최대/최소값)
        - [ ] 비동기 작업의 성공/실패 처리
        - [ ] 사용자 인터랙션에 대한 적절한 반응
    validations:
      required: true

  - type: textarea
    id: existing_tests
    attributes:
      label: 📋 기존 테스트 현황
      description: 이미 존재하는 테스트나 테스트 설정이 있다면 알려주세요.
      placeholder: |
        예시:
        - Jest 설정이 이미 되어있음
        - React Testing Library 사용 중
        - __tests__ 폴더에 일부 테스트 존재
        - package.json에 테스트 스크립트 설정됨
        - 특정 컴포넌트는 이미 테스트 작성됨

  - type: dropdown
    id: test_framework
    attributes:
      label: 🛠️ 선호하는 테스트 도구
      description: 사용하고 싶은 테스트 프레임워크나 도구가 있나요?
      options:
        - Jest + React Testing Library
        - Vitest + Testing Library
        - Cypress (E2E)
        - Playwright (E2E)
        - Storybook (Component)
        - 기존 설정 사용
        - 추천해주세요
      default: 0
    validations:
      required: true

  - type: textarea
    id: test_data
    attributes:
      label: 📊 테스트 데이터
      description: 테스트에 필요한 목 데이터나 픽스처가 있다면 설명해주세요.
      placeholder: |
        예시:
        - 블로그 포스트 샘플 데이터
        - 사용자 인증 정보 목
        - API 응답 데이터 목
        - 파일 시스템 목
        - 외부 서비스 응답 목

  - type: dropdown
    id: coverage_goal
    attributes:
      label: 📈 커버리지 목표
      description: 테스트 커버리지 목표가 있나요?
      options:
        - 🟢 기본 (주요 기능만)
        - 🟡 보통 (70-80%)
        - 🔴 높음 (90%+)
        - 특정 기능만 집중
        - 커버리지 상관없음
      default: 1
    validations:
      required: true

  - type: textarea
    id: test_requirements
    attributes:
      label: 📋 테스트 요구사항
      description: 테스트 작성 시 특별히 고려해야 할 사항이 있나요?
      placeholder: |
        예시:
        - 실제 API 호출 대신 목 사용
        - 브라우저 환경에서만 동작하는 기능 테스트
        - 접근성 테스트 포함
        - 성능 테스트 포함
        - 모바일 환경 테스트
        - 다국어 지원 테스트

  - type: textarea
    id: success_criteria
    attributes:
      label: 🎯 성공 조건
      description: 테스트 작성이 완료되었다고 판단할 수 있는 조건들을 명시해주세요.
      placeholder: |
        예시:
        - [ ] 모든 테스트가 통과함
        - [ ] 커버리지 목표 달성
        - [ ] CI/CD 파이프라인에서 자동 실행
        - [ ] 주요 기능별 테스트 케이스 작성 완료
        - [ ] 에러 시나리오 테스트 포함
        - [ ] 코드 리뷰 통과

  - type: textarea
    id: additional_notes
    attributes:
      label: 📝 추가 정보
      description: 테스트 작성에 도움이 될 추가 정보나 참고사항이 있나요?
      placeholder: |
        예시:
        - 관련 문서나 가이드 링크
        - 참고할 다른 프로젝트의 테스트 코드
        - 특정 버그나 이슈 히스토리
        - 성능 요구사항
        - 팀 내 테스트 컨벤션